### ISSUE TITLE
Unicode text issue

### ISSUE THREAD

**Issue by andre2007** [AngusJohnson/Image32#112]
Hi,

I have an svg (please see attached zip file) which is rendered by edge like this:
<img width="511" alt="image" src="https://github.com/user-attachments/assets/4c71b136-ee58-4645-815e-fab9d6973afe">

In my application it is rendered like this, although I load the needed font "Leipzig" which is specified in the SVG file:
<img width="316" alt="image" src="https://github.com/user-attachments/assets/c6ee5fa6-7bbf-4d31-b66f-eb63f8c166ed">

Within the SVG file, the source code looks like this:
```xml
 <tspan font-family="Leipzig" font-size="720px"></tspan>
 ```
 
 By using online unicode tools, I can see that the character in question is U+EA64
 
 Are these unicode characters in general supported by Image32, or isn't it supported?
 
[sample.zip](https://github.com/user-attachments/files/17939810/sample.zip)

(Leipzig font can be found here https://github.com/rism-digital/leipzig)

 Kind regards
 André

**Comment by andersmelander** [comment]
As far as I can tell it does render the glyph but it probably miscalculates the font base line because it does so waaaay outside the bitmap .

The following is a comparison between how GDI DrawText and Image32 renders the font at 28pt (GDI top, Image32 bottom):
![billede](https://github.com/user-attachments/assets/b92499a7-8a2c-4176-a8d3-eed00b9cc0b9)

**Comment by andre2007** [comment]
@andersmelander thanks for having a look.

From your description, I am not sure whether I understand it correctly. Does it somehow work on your side?

For a moment I thought, maybe the issue is solved with the recent main branch, especially with the commit #111 (Img32.Text: Added support for 4-byte chars (USC-4))
But also with recent main branch it doesn't work on my side.

**Comment by andersmelander** [comment]
> Does it somehow work on your side?

No, I can't really say that it does. Drawing the text directly, using Image32's `DrawText` method, _does_ display the glyph but I haven't tried doing so via a SVG.

The whole metric thing was a red herring; While there does seem to be a slight problem it isn't relevant to this problem. I can see from your screenshot that Image32 displays the "missing glyph" symbol at the correct position so the problem is more that it can't find the glyph or is using the wrong font.

**Comment by AngusJohnson** [comment]
> so the problem is more that it can't find the glyph or is using the wrong font.

I've found the problem and will upload the fix shortly. (Just checking a few other things before doing so.)

**Comment by andre2007** [comment]
@AngusJohnson  
Thank you so much for your quick help.
This looks now fantastic.
