### ISSUE TITLE
Vectorize works but saves weird things to SVG

### ISSUE THREAD

**Issue by Dingo64** [AngusJohnson/Image32#26]
```
uses  ..., SimpleSvgWrite, Img32, Img32.Vector, Img32.Extra, Img32.Draw, Img32.Fmt.BMP, Img32.Fmt.SVG;

var Img: TImage32;
    RawPaths: TPathsD;
    flattenedPaths, bezierPaths: TPathsD;
    simplifiedPaths: TPathsD;
    Svg: TSimpleSvgWriter;
begin
  Img := TImage32.Create;
  Img.LoadFromFile('test.bmp');

  RawPaths := Vectorize(Img, $FF000000, @CompareRGB, $44);

  flattenedPaths := rawPaths;

  DrawPolygon(Img, flattenedPaths, frEvenOdd, clNavy32);
  Img.SaveToFile('out.bmp');

  Svg := TSimpleSvgWriter.Create(frEvenOdd);
  Svg.AddPaths(flattenedPaths, false, $40000033, $FF000033, 1.2);

  Svg.SaveToFile('test.svg');
  Svg.Free;
  Img.Free;

```

out.bmp shows correct image, test.svg shows a single line. Code tested in Lazarus.

**Comment by AngusJohnson** [comment]
I can't help without seeing your `test.bmp`.

**Comment by Dingo64** [comment]
[test.zip](https://github.com/AngusJohnson/Image32/files/11707553/test.zip)

**Comment by AngusJohnson** [comment]
I've just remembered that some time ago I removed `Img32.SVG.Writer.pas` from **Image32** because it was too primitive to justify its presence. However, in my [Clipper2](https://github.com/AngusJohnson/Clipper2) library, there's a [Clipper.SVG.pas](https://github.com/AngusJohnson/Clipper2/blob/main/Delphi/Utils/Clipper.SVG.pas) file that should be easy to adapt to create SVG images from **Image32**'s `TPathD` and `TPathsD` arrays.
